sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3303885692
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: web-xia-tlias
    access-key-id: LTAI5tFadrYVTe3njrwbY2Ai
    access-key-secret: Q0HBDXn94B72iHXfx5pIMGzexyjqcB
  redis:
    host: localhost
    port: 6379
    password: 3303885692
  wechat:
    appid: wxbc90f5c70e393839
    secret: fe6b5e702fb78c51685bce1d5ea01cfe